### ISSUE TITLE
代码运行不了，救救我！

### ISSUE THREAD

**Issue by Smilefish1** [murray-z/OneStop_QAMaker#5]
一直报IndexError: Target 25837 is out of bounds错误，一直改不好，救救孩子吧

**Comment by murray-z** [comment]
修改了哪里吗？

**Comment by Smilefish1** [comment]
大佬，help me!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "murray-z/OneStop_QAMaker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 晚上10:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [murray-z/OneStop_QAMaker] 代码运行不了，救救我！ (Issue #5)





 
修改了哪里吗？

**Comment by murray-z** [comment]
> 运行起来有问题，不知道哪里出错了，大佬可以出来解释一下吗 一直报IndexError: Target 25837 is out of bounds错误

看下transformers版本对不对呢

**Comment by Sunnylee0101** [comment]
代码运行是有问题的，主要的原因是需要把vocab_size=21128这个参数还有onestop_qamaker.py文件中的21128修改为51272，这样就可以运行了，记得运行时关闭梯子。我已经运行了一个权重模型，测试了一下效果并不明显，可能是数据量不够大的原因，需要的可以私聊我

**Comment by 3300752199** [comment]
> 代码运行是有问题的，主要的原因是需要把vocab_size=21128这个参数还有onestop_qamaker.py文件中的21128修改为51272，这样就运行了，记得运行时可以关闭梯子。我已经运行了一个权重模型，测试效果不明显，可能是数据量不够大的原因，需要的可以私聊我

你好，你数据增加了吗 最后效果怎么样啊

**Comment by yanshuaibupt** [comment]
> 

确实好用，我最近在找QAG好用的模型，您有什么推荐的模型吗，我试了试[Transformer-QG-on-SQuAD](https://github.com/p208p2002/Transformer-QG-on-SQuAD)在英文的效果不错，中文模型还没找到特别好的

**Comment by yanshuaibupt** [comment]
@Sunnylee0101 点赞，确实好用，我最近在找QAG好用的模型，您有什么推荐的模型吗，我试了试[Transformer-QG-on-SQuAD](https://github.com/p208p2002/Transformer-QG-on-SQuAD)在英文的效果不错，中文模型还没找到特别好的

**Comment by Sunnylee0101** [comment]
> 

已经放弃这个模型啦，效果挺一般，最主要的问题就是，生成Q还行，但是生成的A很短，一般就几个字，不符合应用场景

**Comment by Sunnylee0101** [comment]
> 

我也在找相关的项目和文献，目前没有什么很好的这种QA生成项目，只能通过调用ChatGPT去生成一些，然后人为的去筛选，其他没什么好的方法了，这块研究的还是很少

**Comment by 3300752199** [comment]
> > 
> 
> 我在找相关的项目和文献，目前没有什么很好的这类QA生成项目，只能通过ChatGPT去生成一些，然后人去筛选，调用其他没有好的方法了，这块研究的还是很少
好的，我现在也在调用chatgpt，目前用的是哪个revchatgpt，可以逆向免费调用。

**Comment by murray-z** [comment]
用开源大模型微调一下，效果还可以！
